### ISSUE TITLE
feat(redis): Redis版本文件 新增一个  RedisDTS 的项，便于上传RedisDTS介质

### ISSUE THREAD

**Issue by lukemakeit** [TencentBlueKing/blueking-dbm#259]
**你想要什么功能**
Redis版本文件 新增一个  RedisDTS 的项，便于上传RedisDTS介质

**建议如何实现**
<img width="1450" alt="image" src="https://github.com/TencentBlueKing/blueking-dbm/assets/14859257/5d876402-8a81-4753-b7f1-77b68b5f3d95">

**Comment by zhangzhw8** [comment]
DTS 属于 cloud 组件，后续建设云区域相关功能时，单独管理，暂不放在 Redis 的版本文件里面了
