### ISSUE TITLE
fix(backend): 优化集群容量状态同步任务

### ISSUE THREAD

**Issue by zhangzhw8** [TencentBlueKing/blueking-dbm#2680]
1. `CACHE_CLUSTER_STATS` 缓存了所有集群的状态，而使用的地方是集群列表，建议按 cluster_type 进行缓存
2. 目前`query_cap`查不出数据，确认下查询参数是否正确
3. 不管什么`cluster_type`的容量查询，查询都带上了 influxdb db，不合理
4. 后续如果环境内存在上万的集群，用 `cluster_type` 去查询监控是否会很慢？

**Comment by zhangzhw8** [comment]
## 关联研发信息
dev_branch: fix/sync_cluster_stat_from_monitor/#2680
target_branch: v1.3.0

**Comment by gaohongsong** [comment]
## 关联研发信息
dev_branch: fix/sync_monitor_stat/#2680
target_branch: v1.3.0
