### ISSUE TITLE
[FEATURE] 能否支持pgsql协议

### ISSUE THREAD

**Issue by DomineCore** [TencentBlueKing/blueking-dbm#338]
**你想要什么功能**
pgsql协议的db管理
**为什么需要**
我们有使用postgresql、cockroachdb等遵循pgsql协议的db，非常需要有这种工具
**建议如何实现**

**Comment by zhangzhw8** [comment]
收到，目前我们正在逐步丰富支持的 db 类型，也欢迎加入一起开发
