### ISSUE TITLE
[Doc]部署文档404

### ISSUE THREAD

**Issue by thislyc** [TencentBlueKing/blueking-dbm#6458]
https://github.com/TencentBlueKing/blueking-dbm/blob/v1.5.0/docs/install/dev_deploy.md

**Comment by thislyc** [comment]
helm charts无法部署，私库？

**Comment by zhangzhw8** [comment]
> helm charts无法部署，私库？

是的，目前尚未 public，我们计划在 1024 推出社区版，届时将会 public，敬请期待

**Comment by thislyc** [comment]
@zhangzhw8 你好，部署文档有吗？希望能本地跑了体验一下
