### ISSUE TITLE
[FEATURE] 什么时候发布第一个版本,现在连安装文档都没

### ISSUE THREAD

**Issue by mine1202** [TencentBlueKing/blueking-dbm#911]
**你想要什么功能**

**为什么需要**

**建议如何实现**

**Comment by zhangzhw8** [comment]
你好，感谢关注，本系统目前还处于开发内测阶段
支持容器化部署，依赖蓝鲸平台，可以先参考文档部署蓝鲸平台，再通过 helmfile 的方式部署 dbm
https://bk.tencent.com/docs/markdown/ZH/DeploymentGuides/7.0/beginners_guide.md
